In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-1.08937629e+00,  6.88566388e-01,  3.57745742e-06, -1.44609382e+00,
        2.21152567e+00, -2.43120858e-03, -8.68535163e-01,  1.18868194e+00,
        1.40058266e+00,  2.81826574e+00])

In [7]:
B = np.random.rand(10)
B

array([0.89024946, 0.43680294, 0.56614849, 0.87743717, 0.05399742,
       0.34813708, 0.58810672, 0.65836913, 0.2186982 , 0.13266795])

In [8]:
# Binary function 
np.add(A,B)

array([-0.19912683,  1.12536933,  0.56615207, -0.56865665,  2.26552309,
        0.34570588, -0.28042845,  1.84705107,  1.61928086,  2.95093369])

In [9]:
np.maximum(A,B)

array([0.89024946, 0.68856639, 0.56614849, 0.87743717, 2.21152567,
       0.34813708, 0.58810672, 1.18868194, 1.40058266, 2.81826574])

In [10]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True